export const TaskConstants = {
    GET_REQUEST: "GET_REQUEST",
    GET_SUCCESS: "GET_SUCCESS",
  
    CREATE_REQUEST: "CREATE_REQUEST",
    CREATE_SUCCESS: "CREATE_SUCCESS",
  
    EDIT_REQUEST: "EDIT_REQUEST",
    EDIT_SUCCESS: "EDIT_SUCCESS",
  
    DELETE_REQUEST: "DELETE_REQUEST",
    DELETE_SUCCESS: "DELETE_SUCCESS",
  
    COMPLETE_REQUEST: "COMPLETE_REQUEST",
    COMPLETE_SUCCESS: "COMPLETE_SUCCESS",
  
    UPDATE_REQUEST: "UPDATE_REQUEST",
    UPDATE_SUCCESS: "UPDATE_SUCCESS",

    TASK_CHANGE:"TASK_CHANGE"
  };
  